### ISSUE TITLE
ImportError: No module named 'am'

### ISSUE THREAD

**Issue by zh187185** [lyqun/PU-Net_pytorch#12]
Namespace(alpha=1.0, batch_size=32, decay_step_list=[30, 60], gpu=0, log_dir='logs/test', lr=0.001, lr_clip=1e-06, lr_decay=0.71, max_epoch=100, model='punet', npoint=1024, optim='adam', up_ratio=4, use_bn=False, use_decay=False, use_res=False, weight_decay=0.0005, workers=4)
Traceback (most recent call last):
  File "train.py", line 35, in <module>
    from auction_match import auction_match
  File "/root/python/PU-Net_pytorch/auction_match/__init__.py", line 1, in <module>
    from .auction_match import auction_match
  File "/root/python/PU-Net_pytorch/auction_match/auction_match.py", line 11, in <module>
    am = load(name="am", sources=sources)
  File "/root/miniconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 644, in load
    is_python_module)
  File "/root/miniconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 824, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/root/miniconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 967, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "/root/miniconda3/lib/python3.7/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'am'
When I encounter this error, how should I solve it? I have tried many methods but none of them worked. Please, author, take the time to reply, this is really important to me. Thank you very much.

**Comment by zh187185** [comment]
I am using PyTorch 1.1.0, Python 3.7, Ubuntu 18.04, and CUDA 10.0. I am using a 2080TI GPU because Torch does not support the 30 series. Can you help me with this issue?

**Comment by lyqun** [comment]
Hi, you may try to enter `./auction_match` and run `python auction_match.py` to see if the library can be successfully loaded.

**Comment by zh187185** [comment]
Thank you very much. I'll try it now

**Comment by zh187185** [comment]
root@autodl-container-63904cb222-65708f7e:~/python/PU-Net_pytorch# cd auction_match/
root@autodl-container-63904cb222-65708f7e:~/python/PU-Net_pytorch/auction_match# python auction_match.py 
Traceback (most recent call last):
  File "auction_match.py", line 11, in <module>
    am = load(name="am", sources=sources)
  File "/root/miniconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 644, in load
    is_python_module)
  File "/root/miniconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 824, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/root/miniconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 967, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "/root/miniconda3/lib/python3.7/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'am'
I have already tried testing it, but it still doesn't work. Prior to this, I encountered an issue where "ninja -v" was not found. I resolved this error by searching and changing "ninja -v" to "ninja -version". Previously, there were no issues with compiling or anything else.

**Comment by zh187185** [comment]
You're welcome! If you have any more questions or need further assistance, feel free to ask.

**Comment by zh187185** [comment]
Thank you for taking the time to reply again. I appreciate it.

**Comment by lyqun** [comment]
I have checked this in my environment, and that works for me (python auction_match.py). From the error messages, I guess Python cannot access the compiled files (perhaps it does not have permission to access them). By the way, the errors are raised by imp.find_module. Hence, you can check the documents (https://docs.python.org/3.11/library/imp.html#imp.find_module) and see if there are some possible solutions for you.

**Comment by yasamanparhizkar** [comment]
Has anyone solved this issue?

**Comment by yasamanparhizkar** [comment]
I solved this error. It happened because the 'am' package was not built by PU-Net due to compilation error.
See this issue:
https://github.com/lyqun/PU-Net_pytorch/issues/8#issuecomment-2143849091

**Comment by yasamanparhizkar** [comment]
>  Prior to this, I encountered an issue where "ninja -v" was not found. I resolved this error by searching and changing "ninja -v" to "ninja -version". Previously, there were no issues with compiling or anything else.


I also tried changing `ninja -v` to `ninja --version`; that's exactly why I received the `ImportError: No module named 'am'` error.
`ninja -v` stands for "ninja verbose", not "ninja version". The former means: build a package and show me messages about the progress of building the package. The latter mean: show me what version of ninja I'm using.
Basically, you're skipping the build step by changing  `ninja -v` to `ninja --version`.
