### ISSUE TITLE
about knn_cuda

### ISSUE THREAD

**Issue by lrrll** [lyqun/PU-Net_pytorch#2]
hi why i run the bash test_punet.sh, it happen that "no modul named knn_cuda import KNN"? i run this code with cuda9.0 python 3.6 pytorch1.0

**Comment by lyqun** [comment]
You should install knn_cuda by running
```
pip install --upgrade https://github.com/unlimblue/KNN_CUDA/releases/download/0.2/KNN_CUDA-0.2-py3-none-any.whl
```

For more details, please refer to this repo, https://github.com/unlimblue/KNN_CUDA

Thanks for pointing out, I will update the installation guideline later.

**Comment by lrrll** [comment]
yes i had resolved, but another problem increasing.
i want know whether it must need cuda 10 and torch 1.2; my environment is cuda 9 and torch 1.1; but it raise the problem like this:
PU-Net_pytorch-master$ python eval.py --gpu 0 --resume logs/punet_baseline/punet
_epoch_99.pth
Namespace(batch_size=8, gpu=0, model='punet', resume='logs/punet_baseline/punet_epoch_99.pth', up_ratio=4, use_bn=False, use_res=False, workers=4)
Traceback (most recent call last):
  File "eval.py", line 26, in <module>
    from pointnet2 import pointnet2_utils as pn2_utils
  File "/home/ouc/l-dataset/PU-Net_pytorch-master/pointnet2/pointnet2_utils.py", line 7, in <module>
    import pointnet2_cuda as pointnet2
ImportError: /home/ouc/.conda/envs/pytorch-1.0/lib/python3.6/site-packages/pointnet2-0.0.0-py3.6-linux-x86_64.egg/pointnet2_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonE

baidu say it is because the version of cuda is not match torch

**Comment by lyqun** [comment]
Have you complied `pointnet2` successfully, by running

```
cd pointnet2
python setup.py install 
```

If cuda and pytorch version mis-match, you may need to re-install pytorch following the official document. Refer to this page, https://pytorch.org/get-started/previous-versions/

This repo is tested with torch 1.2, but I think torch 1.1 is ok.

**Comment by xiaolongTang163** [comment]
![image](https://user-images.githubusercontent.com/95483794/203490935-54628aae-8185-4d31-a16e-fa8280cf38b2.png)
![image](https://user-images.githubusercontent.com/95483794/203491278-d9c75434-cc12-42e5-be12-73dd33188fe2.png)
 i run this code with cuda10.0 python 3.6 pytorch1.2

**Comment by xiaolongTang163** [comment]
I have solve this problem by using Ubuntu

**Comment by Ahmoudahmed** [comment]
You should install knn_cuda by this command line 
pip install --upgrade https://github.com/unlimblue/KNN_CUDA/releases/download/0.2/KNN_CUDA-0.2-py3-none-any.whl
